# Exploratory Data Analysis
Perform initial data exploration and visualization.

In [3]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("../survey.csv")
print(df.head())

             Timestamp  Age  Gender         Country state self_employed  \
0  2014-08-27 11:29:31   37  Female   United States    IL           NaN
1  2014-08-27 11:29:37   44       M   United States    IN           NaN
2  2014-08-27 11:29:44   32    Male          Canada   NaN           NaN
3  2014-08-27 11:29:46   31    Male  United Kingdom   NaN           NaN
4  2014-08-27 11:30:22   31    Male   United States    TX           NaN

  family_history treatment work_interfere    no_employees  ...  \
0             No       Yes          Often            6-25  ...
1             No        No         Rarely  More than 1000  ...
2             No        No         Rarely            6-25  ...
3            Yes       Yes          Often          26-100  ...
4             No        No          Never         100-500  ...

                leave mental_health_consequence phys_health_consequence  \
0       Somewhat easy                        No                      No
1          Don't know                     Maybe                      No
2  Somewhat difficult                        No                      No
3  Somewhat difficult                       Yes                     Yes
4          Don't know                        No                      No

      coworkers supervisor mental_health_interview phys_health_interview  \
0  Some of them        Yes                      No                 Maybe
1            No         No                      No                    No
2           Yes        Yes                     Yes                   Yes
3  Some of them         No                   Maybe                 Maybe
4  Some of them        Yes                     Yes                   Yes

  mental_vs_physical obs_consequence comments
0                Yes              No      NaN
1         Don't know              No      NaN
2                 No              No      NaN
3                 No             Yes      NaN
4         Don't know              No      NaN

[5 rows x 27 columns]

In [9]:
df.sample(25)

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
1017,2014-08-29 09:58:55,46,Female (trans),United States,CT,No,No,Yes,Often,More than 1000,...,Don't know,Yes,No,Some of them,Some of them,No,No,No,Yes,NaN
755,2014-08-28 11:26:15,29,Female,United States,OR,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,Yes,No,Maybe,Don't know,No,NaN
1227,2015-02-21 18:54:12,32,Female,Ireland,NaN,No,Yes,No,Never,More than 1000,...,Don't know,Maybe,No,Some of them,Some of them,No,No,Don't know,No,NaN
9,2014-08-27 11:32:43,23,Male,Canada,NaN,NaN,No,No,Never,26-100,...,Don't know,No,No,Yes,Yes,Maybe,Maybe,Yes,No,NaN
995,2014-08-29 09:19:25,35,Male,United Kingdom,NaN,Yes,No,No,Sometimes,1-5,...,Somewhat easy,No,No,Some of them,Yes,No,No,Don't know,No,NaN
859,2014-08-28 17:02:56,32,male,United Kingdom,NaN,No,Yes,Yes,Rarely,6-25,...,Don't know,Yes,Maybe,Some of them,No,No,No,No,No,NaN
320,2014-08-27 14:28:41,41,Male,United States,SD,No,Yes,Yes,Rarely,100-500,...,Somewhat easy,No,No,Some of them,Yes,Maybe,Maybe,Yes,No,NaN
958,2014-08-29 03:08:25,26,Male,United States,CA,No,No,Yes,Rarely,More than 1000,...,Don't know,No,No,Some of them,Some of them,No,Maybe,No,No,NaN
152,2014-08-27 12:41:04,28,male,Poland,NaN,No,No,No,Rarely,6-25,...,Don't know,No,No,Yes,Yes,Maybe,Yes,Yes,No,NaN
1092,2014-08-29 17:35:16,32,Male,United States,TN,No,Yes,Yes,Often,100-500,...,Very difficult,Yes,No,Yes,Yes,No,Yes,No,No,NaN
801,2014-08-28 13:39:40,23,Male,United States,CA,No,Yes,Yes,Sometimes,6-25,...,Very easy,No,No,Some of them,Yes,Maybe,Maybe,Yes,No,NaN
640,2014-08-28 03:15:01,36,Male,Germany,NaN,No,No,No,NaN,26-100,...,Very easy,No,No,Some of them,Yes,Maybe,Maybe,Yes,No,NaN
1104,2014-08-29 23:51:01,45,M,United States,CA,No,No,No,Never,6-25,...,Don't know,Yes,Maybe,Some of them,No,No,Maybe,Don't know,No,NaN
1133,2014-08-31 22:11:48,27,M,New Zealand,NaN,No,No,No,Rarely,26-100,...,Somewhat difficult,Yes,No,No,No,No,Maybe,No,Yes,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
122,2014-08-27 12:33:23,33,Male,United States,MN,No,Yes,Yes,Sometimes,6-25,...,Very easy,No,No,Yes,Yes,No,Maybe,Yes,No,NaN
177,2014-08-27 12:50:57,32,Female,United States,MA,No,No,Yes,Often,6-25,...,Very easy,No,No,Yes,Yes,No,No,Yes,Yes,I am not sure about my company's healthcare be...
439,2014-08-27 15:43:27,29,Male,United States,PA,No,Yes,Yes,Rarely,1-5,...,Somewhat easy,No,No,Yes,Yes,Maybe,Maybe,Yes,No,NaN
919,2014-08-28 19:28:27,22,F,United States,CA,No,Yes,Yes,Often,More than 1000,...,Don't know,Yes,Yes,No,No,No,No,Don't know,No,NaN
1055,2014-08-29 11:40:29,39,Male,United States,WA,No,Yes,Yes,Sometimes,500-1000,...,Very easy,No,No,Some of them,Yes,No,No,Yes,No,NaN
426,2014-08-27 15:35:21,24,Male,United States,TX,No,Yes,Yes,Sometimes,100-500,...,Somewhat difficult,Yes,No,Some of them,Some of them,No,Maybe,No,Yes,NaN
108,2014-08-27 12:28:12,34,m,United States,TN,No,Yes,No,Never,6-25,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
1100,2014-08-29 21:26:44,29,Male,United States,NY,No,No,No,NaN,6-25,...,Don't know,Maybe,No,Some of them,Yes,Maybe,Yes,Don't know,No,NaN
452,2014-08-27 15:54:45,30,male,United States,WA,No,Yes,Yes,Often,More than 1000,...,Very difficult,Yes,No,Some of them,No,No,No,No,Yes,NaN
78,2014-08-27 11:59:31,32,Male,United States,UT,No,Yes,Yes,Sometimes,26-100,...,Somewhat difficult,Yes,No,Some of them,No,No,Yes,No,No,NaN

In [5]:
df.describe()

                Age
count  1.259000e+03
mean   7.942815e+07
std    2.818299e+09
min   -1.726000e+03
25%    2.700000e+01
50%    3.100000e+01
75%    3.600000e+01
max    1.000000e+11

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   object
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   object
 3   Country                    1259 non-null   object
 4   state                      744 non-null    object
 5   self_employed              1241 non-null   object
 6   family_history             1259 non-null   object
 7   treatment                  1259 non-null   object
 8   work_interfere             995 non-null    object
 9   no_employees               1259 non-null   object
 10  remote_work                1259 non-null   object
 11  tech_company               1259 non-null   object
 12  benefits                   1259 non-null   object
 13  care_options               1259 non-null   object
 14  wellness_program           1259 non-null   object
 15  seek_help                  1259 non-null   object
 16  anonymity                  1259 non-null   object
 17  leave                      1259 non-null   object
 18  mental_health_consequence  1259 non-null   object
 19  phys_health_consequence    1259 non-null   object
 20  coworkers                  1259 non-null   object
 21  supervisor                 1259 non-null   object
 22  mental_health_interview    1259 non-null   object
 23  phys_health_interview      1259 non-null   object
 24  mental_vs_physical         1259 non-null   object
 25  obs_consequence            1259 non-null   object
 26  comments                   164 non-null    object
dtypes: int64(1), object(26)
memory usage: 265.7+ KB

In [8]:
df.shape

(1259, 27)

In [10]:
df.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [11]:
df.drop(columns=["comments"], inplace=True)

In [12]:
df.drop(columns=["state"], inplace=True)

In [13]:
df["self_employed"].fillna(
    df["self_employed"].mode()[0],
    inplace=True
)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_68880\1524786698.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["self_employed"].fillna(

In [14]:
df.isnull().sum()

Timestamp                      0
Age                            0
Gender                         0
Country                        0
self_employed                  0
family_history                 0
treatment                      0
work_interfere               264
no_employees                   0
remote_work                    0
tech_company                   0
benefits                       0
care_options                   0
wellness_program               0
seek_help                      0
anonymity                      0
leave                          0
mental_health_consequence      0
phys_health_consequence        0
coworkers                      0
supervisor                     0
mental_health_interview        0
phys_health_interview          0
mental_vs_physical             0
obs_consequence                0
dtype: int64

In [15]:
df["work_interfere"].fillna(
    "Unknown",
    inplace=True
)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_68880\4287315823.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["work_interfere"].fillna(

In [17]:
df.isnull().sum()

Timestamp                    0
Age                          0
Gender                       0
Country                      0
self_employed                0
family_history               0
treatment                    0
work_interfere               0
no_employees                 0
remote_work                  0
tech_company                 0
benefits                     0
care_options                 0
wellness_program             0
seek_help                    0
anonymity                    0
leave                        0
mental_health_consequence    0
phys_health_consequence      0
coworkers                    0
supervisor                   0
mental_health_interview      0
phys_health_interview        0
mental_vs_physical           0
obs_consequence              0
dtype: int64

In [19]:
df.drop(columns=["Timestamp"], inplace=True)

In [20]:
df.sample(25)

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
399,29,Male,Canada,No,No,Yes,Sometimes,100-500,No,Yes,...,Yes,Somewhat easy,Maybe,No,Some of them,Some of them,No,Maybe,Yes,No
700,30,M,United States,No,No,No,Unknown,100-500,No,No,...,Don't know,Don't know,Maybe,No,Some of them,Yes,No,No,Don't know,No
1166,29,Male,United States,No,Yes,Yes,Sometimes,26-100,No,No,...,Don't know,Don't know,Maybe,No,Some of them,No,No,Maybe,Don't know,No
660,20,F,Switzerland,No,No,No,Rarely,More than 1000,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Some of them,No,Maybe,Yes,No
639,49,male,Japan,Yes,Yes,Yes,Sometimes,1-5,Yes,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,Yes
495,23,Female,United States,No,Yes,Yes,Often,More than 1000,No,Yes,...,Don't know,Don't know,Maybe,No,Some of them,Some of them,No,No,Yes,Yes
217,31,M,Canada,Yes,No,No,Unknown,6-25,No,Yes,...,Yes,Very easy,No,No,Some of them,Some of them,No,No,Yes,No
1077,27,Female,United States,No,Yes,Yes,Often,More than 1000,No,Yes,...,Yes,Very difficult,Maybe,No,Yes,Some of them,No,Maybe,No,Yes
240,22,Male,Sweden,No,No,No,Unknown,6-25,No,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Maybe,Maybe,No,No
998,32,Male,United Kingdom,No,No,No,Rarely,500-1000,No,Yes,...,Don't know,Don't know,Yes,No,No,No,No,No,Don't know,No
568,31,male,United States,No,Yes,No,Sometimes,More than 1000,No,Yes,...,Don't know,Somewhat easy,Maybe,No,No,Some of them,No,Yes,No,No
181,26,f,India,Yes,No,No,Sometimes,6-25,No,No,...,Don't know,Somewhat easy,Maybe,Maybe,Some of them,Some of them,No,No,Don't know,No
1039,35,Male,United States,No,No,No,Unknown,6-25,Yes,Yes,...,Don't know,Don't know,No,No,No,No,No,No,Don't know,No
609,27,Male,Australia,No,No,No,Never,1-5,Yes,Yes,...,Don't know,Don't know,Yes,No,No,No,No,Maybe,Don't know,No
245,40,M,United States,No,No,Yes,Sometimes,More than 1000,Yes,Yes,...,Yes,Don't know,Yes,Maybe,No,No,No,Maybe,No,Yes
108,34,m,United States,No,Yes,No,Never,6-25,Yes,Yes,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
483,29,male,United States,No,No,Yes,Rarely,6-25,No,Yes,...,Don't know,Don't know,Maybe,No,Some of them,No,No,Maybe,Don't know,No
131,32,male,United States,No,No,No,Rarely,1-5,Yes,Yes,...,Don't know,Very difficult,Maybe,No,Yes,Some of them,No,Yes,Don't know,No
319,29,male,Latvia,No,No,No,Unknown,26-100,No,Yes,...,Don't know,Somewhat easy,Maybe,Maybe,Some of them,Some of them,No,No,Don't know,No
940,28,Male,United States,No,Yes,Yes,Rarely,More than 1000,No,Yes,...,Don't know,Don't know,Maybe,No,Some of them,No,No,No,No,No
939,44,male,United States,No,Yes,Yes,Sometimes,6-25,Yes,Yes,...,Yes,Somewhat difficult,Maybe,Maybe,Some of them,Yes,No,Maybe,No,No
907,25,female,United States,No,Yes,Yes,Sometimes,More than 1000,No,Yes,...,Don't know,Don't know,Yes,Yes,No,No,No,No,No,No
1114,40,m,United States,No,No,No,Unknown,More than 1000,No,No,...,Don't know,Somewhat easy,Maybe,No,Some of them,Some of them,No,Maybe,Don't know,No
661,27,Male,United Kingdom,No,No,No,Never,1-5,No,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Maybe,Maybe,Don't know,No
569,38,Make,United States,No,Yes,Yes,Sometimes,100-500,No,Yes,...,Don't know,Don't know,Maybe,Maybe,Some of them,No,No,No,Don't know,No

In [22]:
df.to_csv(
    "eda_cleaned.csv",
    index=False
)